test_that("which_replace", {
  expect_identical(which_replace(logical(0)), integer(0))
  expect_identical(which_replace(1), integer(0))
  expect_identical(which_replace(NA_real_), 1L)
  expect_identical(which_replace(c(1, NA, 1)), 2L)
  expect_identical(which_replace(c(NA, 1, NA)), c(1L, 3L))
  expect_identical(which_replace(c(1, NA, 1), ends = FALSE), 2L)
  expect_identical(which_replace(c(NA, 1, NA), ends = FALSE), integer(0))
  expect_identical(which_replace(c(NA, 1, NA), ends = FALSE), integer(0))
  expect_identical(which_replace(c(1, NA, NA, NA, 1)), 2:4)
  expect_identical(which_replace(c(1, NA, NA, NA, 1), max_span = 3), 2:4)
  expect_identical(which_replace(c(1, NA, NA, NA, 1), max_span = 2), integer(0))
  expect_identical(which_replace(c(1, NA, NA, NA, 1), min_gap = 1), 3L)
  expect_identical(which_replace(c(1, NA, NA, NA, 1), min_gap = 2), integer(0))
  expect_identical(which_replace(c(NA, 1, NA, 1, NA)), c(1L, 3L, 5L))
  expect_identical(which_replace(c(NA, 1, NA, 1, NA), ends = FALSE), 3L)
  expect_identical(length(which_replace(dts_data$Value, min_gap = 0L)), 103L)
})

test_that("delay", {
  expect_identical(delay(character(0)), character(0))
  expect_identical(delay(1:3, 0), 1:3)
  expect_identical(delay(1:3, 1), c(NA, 1:2))
  expect_identical(delay(1:3, 3), rep(NA_integer_, 3))
  expect_identical(delay(1:3, -3), rep(NA_integer_, 3))
  expect_identical(delay(1:3, -1), c(2:3, NA))
  expect_identical(delay(1:3, -2L), c(3L, NA, NA))
})

